version: 2.1

jobs:
  backend_test:
    type: docker
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run:
          name: Run Backend Tests
          command: |
            cd Backend
            npm install
            npm test

workflows:
  backend_pipeline:
    jobs:
      - backend_test

