version: 2.1

jobs:
  database_test:
    type: docker
    docker:
      - image: cimg/postgres:16.0
    steps:
      - checkout
      - run:
          name: Run Database Tests
          command: |
            cd database
            # ./run-db-tests.sh

workflows:
  database_pipeline:
    jobs:
      - database_test

