version: 2.1

jobs:
  frontend_test:
    type: docker
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run:
          name: Run Frontend Tests
          command: |
            cd Frontend
            npm install
            npm test

workflows:
  frontend_pipeline:
    jobs:
      - frontend_test

